import { useState } from 'react';
import { Copy, Check, Bot, ArrowLeft, Download } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import FormattedPrompt from './FormattedPrompt';
import SectionCard from './SectionCard';
import SectionConversation from './SectionConversation';
import FadeIn from '../ui/FadeIn';
import type { SectionType, SectionState } from '../../types';
import type { SectionMessage } from '../../lib/apiClient';
import type { Message } from '../../types';

interface MasterPromptBubbleProps {
  message: Message;
  sections: Record<SectionType, SectionState>;
  sectionMessages: Record<SectionType, SectionMessage[]>;
  activeSection: SectionType | null;
  onSelectSection: (type: SectionType | null) => void;
  onGenerateSection: (type: SectionType, userRequest?: string) => void;
  chatId: string | null;
  onLoadSectionMessages: (chatId: string, sectionType: SectionType) => Promise<void>;
}

function formatTimestamp(ts?: number): string {
  if (!ts) return '';
  try {
    return new Date(ts).toLocaleString();
  } catch {
    return '';
  }
}

export default function MasterPromptBubble({
  message,
  sections,
  sectionMessages,
  activeSection,
  onSelectSection,
  onGenerateSection,
  chatId,
  onLoadSectionMessages,
}: MasterPromptBubbleProps) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const prompt = message.prompt ?? message.content;
  const generatedBy = message.generatedBy;

  const handleCopy = async () => {
    if (!prompt) return;
    try {
      await navigator.clipboard.writeText(prompt);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = prompt;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    if (!prompt) return;
    const md = [
      message.summary ? `# Summary\n\n${message.summary}\n` : '',
      message.analysis ? `# Analysis\n\n${message.analysis}\n` : '',
      `# Master Prompt\n\n${prompt}\n`,
    ]
      .filter(Boolean)
      .join('\n');
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'master-prompt.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <FadeIn className="flex items-start gap-3">
      <div className="w-7 h-7 rounded-md bg-secondary-darkSurface border border-secondary-borderGray flex items-center justify-center shrink-0 mt-0.5">
        <Bot className="w-3.5 h-3.5 text-secondary-midGray" />
      </div>

      <div className="flex-1 min-w-0 space-y-2">
        <div className="flex items-center justify-between gap-2">
          <span className="text-small text-secondary-midGray">Assistant</span>
          {message.timestamp ? (
            <span className="text-small text-secondary-midGray">{formatTimestamp(message.timestamp)}</span>
          ) : null}
        </div>

        {/* Compact bubble — single message per generation */}
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
          className="w-full text-left bg-secondary-darkSurface text-primary-light border border-secondary-borderGray rounded-md rounded-tl-sm px-4 py-3 transition-colors hover:border-accent-orange"
        >
          <div className="text-body leading-relaxed font-medium">Master prompt generated.</div>
          <div className="mt-1 text-small text-secondary-midGray/70">
            {generatedBy ? `Generated by ${generatedBy}` : 'Generated'}
            {message.timestamp ? ` · ${formatTimestamp(message.timestamp)}` : ''}
            <span className="ml-1 opacity-60">{expanded ? '▴' : '▾'}</span>
          </div>
        </button>

        <AnimatePresence initial={false}>
          {expanded && (
            <motion.div
              key="detail"
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.22, ease: 'easeOut' }}
              className="overflow-hidden"
            >
              <div className="rounded-md border border-secondary-borderGray bg-primary-dark p-4 space-y-4">
            {activeSection ? (
              <div className="space-y-3">
                <button
                  onClick={() => onSelectSection(null)}
                  className="flex items-center gap-1.5 text-small text-secondary-midGray hover:text-primary-light transition-colors"
                >
                  <ArrowLeft className="w-3.5 h-3.5" />
                  Back to sections
                </button>
                <SectionConversation
                  sectionType={activeSection}
                  state={sections[activeSection]}
                  messages={sectionMessages[activeSection]}
                  onGenerate={(request) => onGenerateSection(activeSection, request)}
                  onLoadMessages={() =>
                    chatId ? onLoadSectionMessages(chatId, activeSection) : Promise.resolve()
                  }
                />
              </div>
            ) : (
              <>
                {message.summary && (
                  <div>
                    <p className="text-small font-semibold tracking-wider uppercase text-secondary-midGray mb-1.5">Summary</p>
                    <p className="text-body text-primary-light leading-relaxed">{message.summary}</p>
                  </div>
                )}

                {message.analysis && (
                  <div>
                    <p className="text-small font-semibold tracking-wider uppercase text-secondary-midGray mb-1.5">Analysis</p>
                    <p className="text-body text-primary-light leading-relaxed">{message.analysis}</p>
                  </div>
                )}

                <FormattedPrompt content={prompt} />

                <div className="flex justify-end gap-2">
                  <button
                    onClick={handleExport}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-small font-medium rounded-md bg-secondary-darkSurface border border-secondary-borderGray text-secondary-midGray hover:text-primary-light transition-colors"
                  >
                    <Download className="w-3 h-3" />
                    Export
                  </button>
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-small font-medium rounded-md bg-secondary-darkSurface border border-secondary-borderGray text-secondary-midGray hover:text-primary-light transition-colors"
                  >
                    {copied ? (
                      <>
                        <Check className="w-3 h-3 text-success-green" />
                        Copied
                      </>
                    ) : (
                      <>
                        <Copy className="w-3 h-3" />
                        Copy Prompt
                      </>
                    )}
                  </button>
                </div>

                <div className="space-y-4">
                  <div className="text-center py-3">
                    <h3 className="text-subheading font-semibold text-primary-light mb-1">
                      Your master prompt is ready
                    </h3>
                    <p className="text-small text-secondary-midGray">
                      Choose a section to dive deeper
                    </p>
                  </div>

                  <div className="flex items-center gap-3">
                    <div className="flex-1 h-px bg-secondary-borderGray" />
                    <span className="text-small font-medium text-secondary-midGray tracking-wider uppercase">
                      Sections
                    </span>
                    <div className="flex-1 h-px bg-secondary-borderGray" />
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                    {(['coding', 'ui-ux', 'audit'] as SectionType[]).map((type) => (
                      <SectionCard
                        key={type}
                        type={type}
                        state={sections[type]}
                        isActive={false}
                        onClick={() => onSelectSection(type)}
                      />
                    ))}
                  </div>
                </div>
              </>
            )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </FadeIn>
  );
}
